<?php

use App\Photo;
use Illuminate\Database\Seeder;

class PhotosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $photo = new Photo;
        $photo['photo'] = '18.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '19.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '20.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '21.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '22.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '23.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '24.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '25.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '26.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '35.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '36.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '37.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '38.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '39.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '40.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '41.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '42.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '43.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'admin.png';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'user.png';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'subscriber.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '44.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '45.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '46.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '47.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '48.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '49.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '50.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '51.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '52.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '7.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '53.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = '54.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd10.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd11.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd12.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd13.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd14.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd15.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd16.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd17.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd18.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd19.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd20.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd21.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd22.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd23.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd24.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd25.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd26.jpg';
        $photo->save();
        $photo = new Photo;
        $photo['photo'] = 'menProd27.jpg';
        $photo->save();
    }
}
